language: go
install: true
go:
- '1.11'
script:
- go test -v ./...
- "./build.sh -n -u -l -w -t"
notifications:
  email:
  - morfien101@gmail.com
  on_success: change
  on_failure: always
env:
  global:
    secure: aEuc02xkoyqnB2EcaPZKRoVlNqnT/QjqSEfBWJ/MKC82CtVKo7iqWD1TSm2IDy3P9BoxNIFrcQOOFODArjPTDkpelU6HNWcB7svqdUCVITjqVJ0E3OQInA10/o9iuLHqtFXBZNqdX0OKu9Rv7IlKjjmvbBSrj/ccmrz5T7fr8IsuZR6YqMSjfBZGFNN3kGSbeRpNGJYnsRa7R7kYRkyadjGLj38R0xm0uSEXiX/jqPzlp8Wm31mHYWPRbslyYfbwySpDKbc8SLEo/K88qAj8+OvJnJS6GmW0nj0jPEwjwQyVmurllWwIlxmUPGoMl/iX7e/VnCohR5QsREaYkngS09Add6NabhX1XjtMHzy0jjtpgYOkRHMXNmFUS+jzzcMxYt/eb9lPpfDpuiLjWdZ4G+maTuyhRUK5Obaj69ee1hW60ejxUD7BKf1JfC2ui86O1Py4B85YxatZI+/dVkvVXYL45KHOCmNJfqdo+qHlp8Qlahoi8kJzTAOx5RqdhvW6LQ9lO7wWViw4ZWNp1WnXasi+H5NAaDtiiPoaUfmyK1brVOKe0coMLNicKez9lQvgl2K8covyhjLEJTxNsjSDxGcsaItRDz4udLH11bq48C7f3Gi8L2oSe1Zzx43RFSIevk4eda9bdBRUYMHZYoEg1+xjy+/wS44WuH58as+Ktgg=
branches:
  except:
  - "/\\+travis\\d+$/"
before_deploy:
- export PUBDIR=$HOME/publish
- mkdir $PUBDIR
- cp artifacts/*.tar.gz $PUBDIR
- git config --local user.name "Travis"
- git config --local user.email "morfien101@gmail.com"
- git tag "$(./build.sh -v)+travis$TRAVIS_BUILD_NUMBER" --force

