language: go
install: true
go:
- '1.11'
script:
- go test -v ./...
- "./build.sh -n -u -l -w -t"
notifications:
  email:
  - morfien101@gmail.com
  on_success: change
  on_failure: always
env:
  global:
    secure: Pha3EY1cTvCaJwUjLVX2cv0rIoOaFZ7ktjKLqvVSzX1aDy2AdJ1NefsK5n5o8xFQ8zfQj+tyYM7TaLe1XZjlMZgWyJCmoaFkLXGs5tvuaAWUBiyXpX4Zbv/QTS0qP5ydmxMihe+PRL9Mtm+mitgpEyiMrfVzF/6vcGweyy/5CNQVe6bNN5fitsDfLBWMVGSLDdV3fJm3VHmcYUhowU6Soo0vyMkvoqpp1G51eOKZVLcZJMBwuXbxQAlXc0KERVF69h6Fpqy7ScJ2d29pZRjn/Bb0HsqGnEAAPYllt85wjH4nedpPn6U/b9ZMvybK27xzHUBtEnh9NjbLna/IDR/p9xhVjc+cLTNvkPiVn/XtQ5lHrwrcR34whWtZPZW/4ho6t/KBno5OJpfHPzb2ILQEszsAVNPKo3DXoFMZ4KTSn9G39uErLtZ1KK9UrXr97L4G+IewxztXh/PKTYkqMp1dGSzOom8L14I4a2u3SrXQ7DLddSu4J31lr8XpZLeNjtNrA9xr7RJRMriep5OAmSQlXmxmj6mf9GkkMGNrJK74csxXUPpnx5F2oj5Ug9KXyFmNaPpI8dIWyTZS7ax66laVS94PFyugoDq8mojnvQ3Z7gWntdyjRYketeDqPXOqbEPSGbpg1LFxtmkHfNB5Y3526yKAPPEGJ6xCYgAmjWLWD7A=
branches:
  except:
  - "/\\+travis\\d+$/"
before_deploy:
- export PUBDIR=$HOME/publish
- mkdir $PUBDIR
- cp artifacts/*.tar.gz $PUBDIR
- git config --local user.name "Travis"
- git config --local user.email "morfien101@gmail.com"
- git tag "$(./build.sh -v)+travis$TRAVIS_BUILD_NUMBER" --force
deploy:
  provider: releases
  api_key:
    secure: Fg4rRFCtFrYefvZ4pMLcD1x7SJQehONz0nOwzOZD5BvVD3f28o3RBCriduebsXAL23d576X4Ee9gL1yL8kzLKdCGx1BxkVeMt6g4fQWsw+XIzC8gk9hJSVjWWQIgprTasWxlpGhVMgfN50HIGt0+Ka4HGkjF3VxG4/opWQX9eBxeyfbIgX2N1DUfsja2yQvAoKNoxBQcm6dqhv5mKx9NpG0PTkoJWAXKgeA84IeVAef1lJmgFI7R7nxbLCsX2vjZPryXNBFLMX9xjxJeVAW3M6hyn4BnWUnE60LPctTHBwGHxfcBe+cG0c72Z3ylbBSC+XFHvYk1Uz7qXj10/ELLZ58uAFCB3N/o3rhrBpIzCDhF6zFU/gt2YT2+/86UR0M7WYbixIKd12xTQv6gJo4ep+ymG/0QmMuoAatEDb+SVm2mpcl2pCfl+lR0RbnQLIjz+Zbj3U27LaCTQjRTSn7D5v5EnyKcZynYFjpi9f/eSaoD3xCny9OPz+hgoOyTxwLB7yxO9T5c8HnNMEnVy3cdBuQ/mwE7ek0q6BsIBGTYZnzp3hGRriWG5IUte6BjYMayjZg5EXaWLc3mG4mx7M1SpY5/qEB7H5mjupDvm5xA0o7cpLhfNGpLimCGPAvU31iBk8DlTsfovg9SxHQezRTQdTTiF+PUocKbpvRFv0fkPug=
  file: 
    - $HOME/publish/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: morfien101/chef-waiter
