language: go
install: true
go:
- '1.11'
script:
- export PUBDIR=$HOME/publish
- mkdir $PUBDIR
- go test -v ./...
- "./build.sh -n -u -l -w"
notifications:
  email:
  - morfien101@gmail.com
  on_success: change
  on_failure: always
env:
  global:
    secure: Pha3EY1cTvCaJwUjLVX2cv0rIoOaFZ7ktjKLqvVSzX1aDy2AdJ1NefsK5n5o8xFQ8zfQj+tyYM7TaLe1XZjlMZgWyJCmoaFkLXGs5tvuaAWUBiyXpX4Zbv/QTS0qP5ydmxMihe+PRL9Mtm+mitgpEyiMrfVzF/6vcGweyy/5CNQVe6bNN5fitsDfLBWMVGSLDdV3fJm3VHmcYUhowU6Soo0vyMkvoqpp1G51eOKZVLcZJMBwuXbxQAlXc0KERVF69h6Fpqy7ScJ2d29pZRjn/Bb0HsqGnEAAPYllt85wjH4nedpPn6U/b9ZMvybK27xzHUBtEnh9NjbLna/IDR/p9xhVjc+cLTNvkPiVn/XtQ5lHrwrcR34whWtZPZW/4ho6t/KBno5OJpfHPzb2ILQEszsAVNPKo3DXoFMZ4KTSn9G39uErLtZ1KK9UrXr97L4G+IewxztXh/PKTYkqMp1dGSzOom8L14I4a2u3SrXQ7DLddSu4J31lr8XpZLeNjtNrA9xr7RJRMriep5OAmSQlXmxmj6mf9GkkMGNrJK74csxXUPpnx5F2oj5Ug9KXyFmNaPpI8dIWyTZS7ax66laVS94PFyugoDq8mojnvQ3Z7gWntdyjRYketeDqPXOqbEPSGbpg1LFxtmkHfNB5Y3526yKAPPEGJ6xCYgAmjWLWD7A=
branches:
  except:
  - "/\\+travis\\d+$/"
before_deploy:
- cp ./artifacts/*.tar.gz ./publish 
- git config --local user.name "Travis"
- git config --local user.email "morfien101@gmail.com"
- git tag "$(./build.sh -v)+travis$TRAVIS_BUILD_NUMBER" --force
deploy:
  provider: releases
  api_key:
    secure: Pha3EY1cTvCaJwUjLVX2cv0rIoOaFZ7ktjKLqvVSzX1aDy2AdJ1NefsK5n5o8xFQ8zfQj+tyYM7TaLe1XZjlMZgWyJCmoaFkLXGs5tvuaAWUBiyXpX4Zbv/QTS0qP5ydmxMihe+PRL9Mtm+mitgpEyiMrfVzF/6vcGweyy/5CNQVe6bNN5fitsDfLBWMVGSLDdV3fJm3VHmcYUhowU6Soo0vyMkvoqpp1G51eOKZVLcZJMBwuXbxQAlXc0KERVF69h6Fpqy7ScJ2d29pZRjn/Bb0HsqGnEAAPYllt85wjH4nedpPn6U/b9ZMvybK27xzHUBtEnh9NjbLna/IDR/p9xhVjc+cLTNvkPiVn/XtQ5lHrwrcR34whWtZPZW/4ho6t/KBno5OJpfHPzb2ILQEszsAVNPKo3DXoFMZ4KTSn9G39uErLtZ1KK9UrXr97L4G+IewxztXh/PKTYkqMp1dGSzOom8L14I4a2u3SrXQ7DLddSu4J31lr8XpZLeNjtNrA9xr7RJRMriep5OAmSQlXmxmj6mf9GkkMGNrJK74csxXUPpnx5F2oj5Ug9KXyFmNaPpI8dIWyTZS7ax66laVS94PFyugoDq8mojnvQ3Z7gWntdyjRYketeDqPXOqbEPSGbpg1LFxtmkHfNB5Y3526yKAPPEGJ6xCYgAmjWLWD7A=
  file: 
    - publish/*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: morfien101/chef-waiter