language: go
install: true
go:
- '1.11'
script:
- export PUBDIR=$HOME/publish
- mkdir $PUBDIR
- go test -v ./...
- ./build.sh -n -u -l -w
#before_deploy:
#- cp ./artifacts/*.tar.gz ./publish 
#- git config --local user.name "Travis"
#- git config --local user.email "randy.coburn@newvoicemedia.com"
#- git tag "$(./build.sh -v)" --force
#deploy:
#  provider: releases
#  api_key:
#    secure: 
#  file: 
#    - publish/*
#  file_glob: true
#  skip_cleanup: true
#  on:
#    repo: newvoicemedia/chef-waiter
notifications:
  email:
  - randy.coburn@newvoicemedia.com
  on_success: change
  on_failure: always